name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt  # Uncomment if you have dependencies

      - name: Run Python script to generate output
        run: |
          python main.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
          publish_dir: ./ # Publish the current directory containing the output.html
          branch: gh-pages # Deploy to the gh-pages branch
